server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/nuvepro
    username: root
    password: password
    #driver-class-name: com.mysql.jdbc.Driver

